### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by Tirtsah613** [dczhu/crash#1]
Hello,
We are using this GitHub in order to get crash application that match our architecture needs - MIPS64.
As I see, there is a single version - master, so we're using this. (download binaries from here: https://github.com/dczhu/crash/archive/master.zip)
But I wonder, what if you'll update master? will this binaries change accordingly or not? 
If yes - Is there a way to download a fixed  binaries version?

One more question, 
Are you planning to rebase/update this project according to what is being updated in the original project? - this can help us very much, because of there are new interest features that match our needs. for example, extract peripherals related dumps.

Thanks in advance,
Tirtsah.

**Comment by dczhu** [comment]
Hello,


Sorry for my late reply (missed the message).

I have just created an [initial release](https://github.com/dczhu/crash/releases/tag/v1.0) for you to download.

As you can see from the release log, it's rebased on crash-7.2.5, and it addresses all the issues and feature requirements reported by your engineers.

Regarding future rebasement, I'm not tracking the crash tool mainline development. But if you run into any issues when doing so, feel free to submit a ticket through our company's customer portal.


Thanks,

Dengcheng

**Comment by Tirtsah613** [comment]
are master changes made only upon requests reported from my team ?
can you define what you refer to as "team" ? specific names ?

**Comment by dczhu** [comment]
Shirley,  Racheli, Daniel.
This repo holds the fixes and new features that correspond to PP tickets.
